### ISSUE TITLE
Installation error: packages not found

### ISSUE THREAD

**Issue by muety** [ogarcia/sysdweb#1]
I'm getting the following error when trying to `pip install sysdweb` according to your installation instructions. Same when trying to `pip install -r` from source. Are there any further dependecies to install?

- `python --version` --> `Python 3.4.2`
- `pip --version` --> `pip 1.5.6 from /home/myusername/dev/syswebd/lib/python3.4/site-packages (python 3.4)`

```
Package libsystemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd' found

Package libsystemd-journal was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd-journal.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd-journal' found
```

**Comment by ogarcia** [comment]
Hi @n1try 

Are you using CentOS or similar? Try to install `systemd-devel` first.
In Ubuntu the package is `libsystemd-dev`.

Tell me if the issue is solved.

**Comment by muety** [comment]
I'm using Debian. I figured out that I had to install `libsystemd-{journal,daemon,login,id128}-dev gcc python3-dev pkg-config` as described in [systemd/python-systemd](https://github.com/systemd/python-systemd) as well as `libdbus-1-dev`. Maybe you should add that in the description 😊
