### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by ghost** [ogarcia/sysdweb#3]
Is there a way to disable CORS protection so it can be called from the UI of a separately hosted web app? Or any ideas what I'm doing wrong to run into a CORS issue?

**Comment by ogarcia** [comment]
The truth is that I don't know what problems CORS can give you because sysdweb uses bottle and by default it doesn't have any CORS. It seems rather a problem in the UI you are using because if you access it via API with curl it should work correctly.

**Comment by ghost** [comment]
Thank you for the quick reply @ogarcia !

so I have these minimal test codes:
```python
from base64 import b64encode
import requests


def control_service(name, action):
    token = b64encode(b'redacted:redacted').decode("utf-8")
    headers = {"Authorization": f"Basic {token}"}
    print(headers)
    response = requests.get(f"http://0.0.0.0:8008/api/v1/{name}/{action}", headers=headers)
    print(response.text)


control_service("teamviewerd", "status")
```

and

```html
<!DOCTYPE HTML>
<html>
<body>
    <script>
        function controlService(name, action) {
            const token = window.btoa("redacted:redacted");
            const request_config = {
                headers: {
                    Authorization: `Basic ${token}`,
                },
                mode: 'no-cors',
                // mode: 'cors',
                // mode: 'same-origin',
            };
            console.log(request_config)
            return fetch(`http://0.0.0.0:8008/api/v1/${name}/${action}`, request_config);
        }
        controlService('teamviewerd', 'status').then(resp => {
            console.log(resp)
        }).catch(err => {
            console.log(err)
        })
    </script>
</body>
</html>
```

replace `redacted:redacted` with your `username:password` to make it work

So running the Python code locally works perfectly fine but opening the html file in the browser locally does not. It gets a 401 unauthorized error.

```bash
127.0.0.1 - - [29/Apr/2022 10:28:24] "GET /api/v1/teamviewerd/status HTTP/1.1" 200 20
127.0.0.1 - - [29/Apr/2022 10:38:00] "GET /api/v1/teamviewerd/status HTTP/1.1" 401 738
```

Without the `no-cors` option it will get a CORS error.

```bash
127.0.0.1 - - [29/Apr/2022 10:41:07] "OPTIONS /api/v1/teamviewerd/status HTTP/1.1" 405 756 
```

I know that there's also server side configuration to mitigate CORS issues as described here: https://stackoverflow.com/questions/17262170/bottle-py-enabling-cors-for-jquery-ajax-requests

Can you think of any solution?

**Comment by ghost** [comment]
So from what I can see, no-cors mode does not allow authentication headers, I can also see from the browser that the header is not in the actual request. - https://stackoverflow.com/questions/44606244/using-fetch-api-with-mode-no-cors-can-t-set-request-headers

To use the request in cors mode, maybe sysdweb would need to be configured to allow cors connections?

**Comment by ghost** [comment]
I think I found a solution, will post a PR later

**Comment by ghost** [comment]
Updated test code

```
<!DOCTYPE HTML>
<html>
<body>
    <script>
        function controlService(name, action) {
            const token = window.btoa("user:pass");
            const request_config = {
                headers: {
                    'Authorization': `Basic ${token}`,
                },
            };
            console.log(request_config)
            return fetch(`http://0.0.0.0:8008/api/v1/${name}/${action}`, request_config);
        }
        controlService('teamviewerd', 'status').then(resp => {
            resp.body.getReader().read().then(({ done, value }) => {
                console.log(String.fromCharCode.apply(null, value))
            })
        }).catch(err => {
            console.log(err)
        })
    </script>
</body>
</html>
```

**Comment by ogarcia** [comment]
All done. Thanks!!
